name: stb_direct
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  feather_icons: ^1.2.0
  flutter_slider_drawer: ^2.1.3
  lottie: ^2.6.0
  glassmorphism: ^3.0.0
  flutter_credit_card: ^3.0.7
  app_color: ^0.0.6
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/ReadexPro/ReadexPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/ReadexPro/ReadexPro-Light.ttf
          weight: 300
        - asset: assets/fonts/ReadexPro/ReadexPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/ReadexPro/ReadexPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/ReadexPro/ReadexPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ReadexPro/ReadexPro-Bold.ttf
          weight: 700

  assets:
    - assets/
    - assets/icons/
